// Generated by Supabase MCP `generate_typescript_types` on 2026-05-21 against
// project cqfszhxuvvsgusvjdyqx. Regenerate after any migration via:
//
//   gh pr merge <pr> --squash --delete-branch
//   # then via MCP: apply_migration -> generate_typescript_types
//
// Do not edit by hand. The CHECK constraint value-sets do not surface as
// TypeScript string-literal unions; for those, see `Preferences` in
// `src/lib/preferences.ts`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4";
  };
  public: {
    Tables: {
      food_log: {
        Row: {
          calories: number | null;
          carbs_g: number | null;
          created_at: string | null;
          fat_g: number | null;
          id: string;
          log_date: string;
          meal: string;
          notes: string | null;
          portion_amount: number | null;
          portion_g: number;
          portion_unit: string | null;
          protein_g: number | null;
          recipe_id: string | null;
          user_id: string | null;
        };
        Insert: {
          calories?: number | null;
          carbs_g?: number | null;
          created_at?: string | null;
          fat_g?: number | null;
          id?: string;
          log_date?: string;
          meal: string;
          notes?: string | null;
          portion_amount?: number | null;
          portion_g: number;
          portion_unit?: string | null;
          protein_g?: number | null;
          recipe_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          calories?: number | null;
          carbs_g?: number | null;
          created_at?: string | null;
          fat_g?: number | null;
          id?: string;
          log_date?: string;
          meal?: string;
          notes?: string | null;
          portion_amount?: number | null;
          portion_g?: number;
          portion_unit?: string | null;
          protein_g?: number | null;
          recipe_id?: string | null;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "food_log_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      ingredients: {
        Row: {
          calories: number | null;
          carbs_g: number | null;
          category: string | null;
          created_at: string | null;
          fat_g: number | null;
          id: string;
          name: string;
          protein_g: number | null;
          quantity: number | null;
          recipe_id: string;
          unit: string | null;
        };
        Insert: {
          calories?: number | null;
          carbs_g?: number | null;
          category?: string | null;
          created_at?: string | null;
          fat_g?: number | null;
          id?: string;
          name: string;
          protein_g?: number | null;
          quantity?: number | null;
          recipe_id: string;
          unit?: string | null;
        };
        Update: {
          calories?: number | null;
          carbs_g?: number | null;
          category?: string | null;
          created_at?: string | null;
          fat_g?: number | null;
          id?: string;
          name?: string;
          protein_g?: number | null;
          quantity?: number | null;
          recipe_id?: string;
          unit?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "ingredients_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      recipes: {
        Row: {
          cook_time_minutes: number | null;
          created_at: string | null;
          cuisine_tag: string | null;
          dietary_tags: string[] | null;
          id: string;
          image_url: string | null;
          julie_rating: number | null;
          manual_calorie_override: number | null;
          name: string;
          prep_time_minutes: number | null;
          preparation: string | null;
          servings: number | null;
          slug: string;
          source_url: string | null;
          total_batch_weight_g: number | null;
          updated_at: string | null;
          user_id: string | null;
        };
        Insert: {
          cook_time_minutes?: number | null;
          created_at?: string | null;
          cuisine_tag?: string | null;
          dietary_tags?: string[] | null;
          id?: string;
          image_url?: string | null;
          julie_rating?: number | null;
          manual_calorie_override?: number | null;
          name: string;
          prep_time_minutes?: number | null;
          preparation?: string | null;
          servings?: number | null;
          slug: string;
          source_url?: string | null;
          total_batch_weight_g?: number | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Update: {
          cook_time_minutes?: number | null;
          created_at?: string | null;
          cuisine_tag?: string | null;
          dietary_tags?: string[] | null;
          id?: string;
          image_url?: string | null;
          julie_rating?: number | null;
          manual_calorie_override?: number | null;
          name?: string;
          prep_time_minutes?: number | null;
          preparation?: string | null;
          servings?: number | null;
          slug?: string;
          source_url?: string | null;
          total_batch_weight_g?: number | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      user_preferences: {
        Row: {
          imagery: string;
          palette: string;
          paper: string;
          updated_at: string;
          user_id: string;
          voice: string;
        };
        Insert: {
          imagery?: string;
          palette?: string;
          paper?: string;
          updated_at?: string;
          user_id: string;
          voice?: string;
        };
        Update: {
          imagery?: string;
          palette?: string;
          paper?: string;
          updated_at?: string;
          user_id?: string;
          voice?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
