// Ingredient Data Contract — single source of truth for both scraper paths
// (CLI script + web API route). See ADR-002 for rationale.

export const VALID_CUISINES = [
  "American",
  "Moroccan",
  "Italian",
  "Asian",
  "Mediterranean",
  "Other",
] as const;

export const VALID_DIETARY = [
  "Vegetarian",
  "Gluten-Free",
  "Dairy-Free",
  "High Protein",
  "Comfort Food",
] as const;

export const VALID_COOKING_UNITS = [
  "/tsp",
  "/tbsp",
  "/cup",
  "/oz",
  "/lb",
  "/each",
  "/can",
] as const;

export const VALID_CATEGORIES = [
  "Produce",
  "Meat",
  "Fish",
  "Dairy",
  "Spice",
  "Pantry",
  "Grocery",
  "Bakery",
  "Other",
] as const;

export type Cuisine = (typeof VALID_CUISINES)[number];
export type Dietary = (typeof VALID_DIETARY)[number];
export type CookingUnit = (typeof VALID_COOKING_UNITS)[number];
export type Category = (typeof VALID_CATEGORIES)[number];

export const UNIT_MAP: Record<string, CookingUnit> = {
  cups: "/cup",
  cup: "/cup",
  oz: "/oz",
  ounce: "/oz",
  ounces: "/oz",
  lb: "/lb",
  lbs: "/lb",
  pound: "/lb",
  pounds: "/lb",
  can: "/can",
  cans: "/can",
  each: "/each",
  whole: "/each",
  piece: "/each",
  pieces: "/each",
  cloves: "/each",
  clove: "/each",
  tbsp: "/tbsp",
  tablespoon: "/tbsp",
  tablespoons: "/tbsp",
  tsp: "/tsp",
  teaspoon: "/tsp",
  teaspoons: "/tsp",
};

export const CUISINE_MAP: Record<string, Cuisine> = {
  "Middle Eastern": "Mediterranean",
  French: "Other",
  Mexican: "Other",
  Indian: "Other",
  Japanese: "Asian",
  Chinese: "Asian",
  Thai: "Asian",
  Korean: "Asian",
  Vietnamese: "Asian",
};

export const CANONICAL_NAMES: Record<string, string> = {
  "extra-virgin olive oil": "olive oil",
  "extra virgin olive oil": "olive oil",
  evoo: "olive oil",
  "large eggs": "egg",
  "large egg": "egg",
  eggs: "egg",
  carrots: "carrot",
  onions: "onion",
  potatoes: "potato",
  "sweet potatoes": "sweet potato",
  "bell peppers": "bell pepper",
  "red bell peppers": "red bell pepper",
  strawberries: "strawberry",
  blueberries: "blueberry",
  lentils: "lentil",
  chickpeas: "chickpea",
  tomatoes: "tomato",
  "green onions": "green onion",
  "cloves garlic": "garlic",
  "garlic cloves": "garlic",
  "chicken breasts": "chicken breast",
  "chicken thighs": "chicken thigh",
  "hamburger buns": "hamburger bun",
  "dried apricots": "dried apricot",
  "golden raisins": "golden raisin",
  "slivered almonds": "slivered almond",
};

export const KEEP_WITH_ADJECTIVE = [
  "sweet potato",
  "fresh parsley",
  "fresh ginger",
  "dried apricot",
  "dried thyme",
  "red bell pepper",
  "red pepper flakes",
  "red wine vinegar",
  "brown sugar",
  "brown rice",
  "sharp cheddar",
  "colby jack cheese",
  "diced tomatoes",
  "crushed tomatoes",
];

export const CATEGORY_MAP: Record<string, Category> = {
  onion: "Produce",
  garlic: "Produce",
  carrot: "Produce",
  "bell pepper": "Produce",
  "red bell pepper": "Produce",
  zucchini: "Produce",
  "sweet potato": "Produce",
  lemon: "Produce",
  blueberry: "Produce",
  strawberry: "Produce",
  "collard greens": "Produce",
  broccoli: "Produce",
  "green onion": "Produce",
  "fresh parsley": "Produce",
  "fresh ginger": "Produce",
  "dried apricot": "Produce",
  potato: "Produce",
  tomato: "Produce",
  "russet potato": "Produce",
  "ground beef": "Meat",
  "chicken breast": "Meat",
  "chicken thigh": "Meat",
  egg: "Dairy",
  butter: "Dairy",
  milk: "Dairy",
  "heavy cream": "Dairy",
  "evaporated milk": "Dairy",
  "feta cheese": "Dairy",
  "cheddar cheese": "Dairy",
  "sharp cheddar": "Dairy",
  "colby jack cheese": "Dairy",
  "vanilla ice cream": "Dairy",
  salt: "Spice",
  "black pepper": "Spice",
  cumin: "Spice",
  paprika: "Spice",
  "italian seasoning": "Spice",
  "dried thyme": "Spice",
  "curry powder": "Spice",
  "red pepper flakes": "Spice",
  "sea salt": "Spice",
  "montreal steak seasoning": "Spice",
  "baking powder": "Spice",
  "olive oil": "Pantry",
  "soy sauce": "Pantry",
  honey: "Pantry",
  "maple syrup": "Pantry",
  vinegar: "Pantry",
  "red wine vinegar": "Pantry",
  "rice vinegar": "Pantry",
  "tomato paste": "Pantry",
  "dijon mustard": "Pantry",
  "bbq sauce": "Pantry",
  tamari: "Pantry",
  "chili garlic sauce": "Pantry",
  "toasted sesame oil": "Pantry",
  cornstarch: "Pantry",
  "brown sugar": "Pantry",
  sugar: "Pantry",
  "icing sugar": "Pantry",
  "chocolate sauce": "Pantry",
  "lemon juice": "Pantry",
  "peanut butter": "Pantry",
  "vanilla extract": "Pantry",
  ketchup: "Pantry",
  "all-purpose flour": "Grocery",
  "white rice": "Grocery",
  "brown rice": "Grocery",
  "elbow macaroni": "Grocery",
  "cavatappi pasta": "Grocery",
  couscous: "Grocery",
  lentil: "Grocery",
  chickpea: "Grocery",
  "golden raisin": "Grocery",
  "slivered almond": "Grocery",
  "diced tomatoes": "Grocery",
  "crushed tomatoes": "Grocery",
  "tomato sauce": "Grocery",
  "vegetable broth": "Grocery",
  "chicken broth": "Grocery",
  "beef broth": "Grocery",
  water: "Grocery",
  "extra-firm tofu": "Grocery",
  peas: "Grocery",
  "hamburger bun": "Bakery",
};

export const SPICES = [
  "salt",
  "black pepper",
  "cumin",
  "paprika",
  "italian seasoning",
  "dried thyme",
  "curry powder",
  "red pepper flakes",
  "baking powder",
  "sea salt",
  "montreal steak seasoning",
];

export const SMALL_LIQUIDS = [
  "olive oil",
  "soy sauce",
  "honey",
  "maple syrup",
  "vinegar",
  "red wine vinegar",
  "rice vinegar",
  "tomato paste",
  "dijon mustard",
  "lemon juice",
  "cornstarch",
  "brown sugar",
  "sugar",
  "fresh ginger",
  "bbq sauce",
  "tamari",
  "chili garlic sauce",
  "toasted sesame oil",
  "vanilla extract",
  "ketchup",
];

export const COUNTABLE = [
  "egg",
  "onion",
  "garlic",
  "bell pepper",
  "red bell pepper",
  "carrot",
  "zucchini",
  "lemon",
  "hamburger bun",
  "potato",
  "tomato",
  "sweet potato",
  "dried apricot",
  "strawberry",
  "green onion",
];

export const NO_PLURAL_STRIP = [
  "peas",
  "collard greens",
  "diced tomatoes",
  "crushed tomatoes",
  "red pepper flakes",
  "golden raisins",
  "slivered almonds",
];
